# Generated by Django 4.1.1 on 2022-09-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accessory_type',
            field=models.CharField(blank=True, choices=[('w', 'Watch'), ('B', 'Bag'), ('GL', 'Glass')], max_length=2),
        ),
    ]
