# Generated by Django 4.1.1 on 2022-09-27 08:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_accessory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='colour',
            field=models.CharField(default='Black', max_length=10),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='size',
            field=models.CharField(default='S', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Pink', 'Pink'), ('BLue', 'Blue'), ('Gold', 'Gold'), ('Black', 'Black'), ('Red', 'Red'), ('Orange', 'Orange')], max_length=31),
        ),
    ]
